version: '3.9'
services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
  web:
    image: tautiz/web4study:latest
    volumes:
      - ./failai:/var/www/html/
    ports:
      - "80:80"
    environment:
      PHP_IDE_CONFIG: 'serverName=php.local'
      APACHE_SERVER_NAME: php.local
      APPLICATION_ENV: development
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - myapp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: duombaze
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass

volumes:
  myapp:
    external: false